# Generated by Django 4.0.6 on 2022-08-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.member')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.slot')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
            ],
        ),
    ]
